### PR TITLE
improved install process

### PR DESCRIPTION
**Pull request by andiderp**

### CODE REVIEW

**Comment by rmgk** [comment]
the main reason for the weird project layout was to have the tests in a different eclipse project than the tested macros, as the eclipse compiler did not do separate compilation for tests and macros.
is that fixed by now? 

also i am not to keen on adding IDE plugins to the project, i think its better to have people do a local install for those plugins.

lastly, thea reason for 

```scala
libraryDependencies ++= (
  a ::
  b ::
  c ::
  Nil)
```
is so that one can add, remove and sort the dependencies on a line by line basis, without having to shuffle the missing comma on the last line around. i am open to reasons why the other style should be preferred.

**Comment by andiderp** [comment]
The eclipse compiler still can't handle separate compilation. I will revert this change.

I was told by Guido to make the installation process easier and to create the possibility of creating a Eclipse project via sbt eclipse. I think it doesn't hurt to have at least one IDE plugin. Eclipse is the standard Scala IDE so it is usefull that you can just run sbt eclipse and don't have to look up the sbt documentation.

The other style is better to read and you don't shuffle those dependencies around on a daily basis, so there is no need for this ugly syntax.

**Comment by rmgk** [comment]
i never heard anyone try if the current sbt project can be converted to eclipse,
so i just assume it also does not work.
i would be happy if someone with some knowledge about eclipse could make it work :)

**Comment by andiderp** [comment]
After deciding to add the eclipse plugin locally and because Eclipse can't handle separate compilation for test and main. This changes are useless.

**Pull request closed without merging**
